### PR TITLE
Update nl.js

### PR DESCRIPTION
**Pull request by dofl**
Corrected incorrect grammar

### CODE REVIEW

**Comment by Jasperrr91** [comment]
It should be `Uitloggen bij` not `Uitloggen uit`. And maybe `Voer` instead of `Vul.

**Comment by brantje** [comment]
Translations are handles by [Transifex](https://www.transifex.com/nextcloud/nextcloud/passman/)

**Comment by dofl** [comment]
Seems like missing the point of the github and the community contributions.

**Comment by brantje** [comment]
Not really. You can login with your **github** account and start editing, no need for extra account.
We already have ~1000 translators in the nextcloud team. Who all are community contributors and translating passman / nextcloud to 72 different languages. 

image


Why use transifex? Because for us is way easier to manage translations. Some people can't write json / js, but can do translations. This way everybody (even non coders) can help translating passman / nextcloud.

Shall we get started?
First of all  go to [here](https://www.transifex.com/nextcloud/nextcloud/passman/), and login with your github account. After setup is done you're reedy to join the Nextcloud transifex team!

image

On the right side click `Join team`. You will get a popup asking what languages you speak.
Do this for every language you speak. After that press F5 to get the dashboard, resources and announcements.

Click on Resources. 
This page lists every single Nextcloud app using transifex. This way you can help with other apps too!

If you have any questions left,, feel free too ask.

**Pull request closed without merging**
