### PR TITLE
Add rel="nofollow noopener noreferrer"

### PR DESCRIPTION
**Pull request by EdOverflow**
For more on reverse tabnabbing, please refer to the following page: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

### CODE REVIEW

**Comment by brantje** [comment]
Great find! Thanks

**Comment by brantje** [comment]
Seems like Scrutinizer / Travis are being lazy.
Since this is a small change i don't see any point waiting for them.

**Comment by maestroi** [comment]
Thanks man great find!

**Comment by brantje** [comment]
Uch, no need to rebase, i wanted to sign you commit, apparently git was thinking different.
I've re-commited your fix and included your name.

I saw that you forgot your name at the contributor list, is this intended or not?

Thanks again for your contribution its much appreciated.

**Pull request closed without merging**
