### PR TITLE
Spelling: Passman, Docker, PayPal, bitcoin

### PR DESCRIPTION
**Pull request by comradekingu**
As per https://passman.cc/
https://www.docker.com/
https://www.paypal.com
https://en.wikipedia.org/wiki/Bitcoin#Etymology_and_orthography

### CODE REVIEW

**Comment by brantje** [comment]
As stated in the other PR, you need to sign your commits before we can merge them.
Can you please do this?

**Comment by comradekingu** [comment]
@brantje I dont have the pass for my PGP key.

**Comment by brantje** [comment]
Afaik, if i merge with rebase your commits get signed, is this true @animalillo ?

**Comment by animalillo** [comment]
yep

**Comment by brantje** [comment]
Due lack of signing i squashed merged this. Ref: 2fd8dc9b8675419bc25ec861aa85f01a81f8fab7

**Pull request closed without merging**
