### PR TITLE
Add Padlock importer

### PR DESCRIPTION
**Pull request by bingen**
Importer for the CSV export files of Padlock password manager:
https://padlock.io/

Signed-off-by: ßingen <bingentxu@gmail.com>

### CODE REVIEW

**Comment by brantje** [comment]
Thanks for your PR! We will review it asap.

**Comment by brantje** [comment]
Can you fix those scrutinizer issues:
image
Other than that, neat :+1:

**Comment by bingen** [comment]
Done.

**Comment by brantje** [comment]
Thanks for your contribution!

**Pull request merged**
