### PR TITLE
fix NC16 compatibility

### PR DESCRIPTION
**Pull request by Bubu**
Caveat: I've no idea if that is the right fix. All I can say is that I'm running this in production for a few weeks now and no-one complained that passman isn't working yet.

### CODE REVIEW

**Comment by newhinton** [comment]
@Bubu

this is great! However, i cannot create a "proper" release, with an update for nextcloud

But: i will test this, and merge it if it is working as intended

If i have not done so by sunday evening, feel free to push ;)

**Comment by e-alfred** [comment]
> this is great! However, i cannot create a "proper" release, with an update for nextcloud

Can you publish a new release at least on the Github releases page so there is at least an updated package available?

**Comment by newhinton** [comment]
@Bubu I am sorry to inform you that i need you to recreate this pull request. It was not signed, and i overlooked that it was not. We require you to sign this before we can merge it to the master branch. I would still like to include your code in passman, could you recreate it signed and then open another pull request? That would be very helpful! Sorry!

**Comment by Bubu** [comment]
> It was not signed,

It was actually.  (Not in the first iteration but I force-pushed to this merge request after the bot told me it needed to be signed.)

(And I actually wondered at that time, can a contribution that solely removes code actually be under copyright? :thinking: )

**Pull request merged**
