### PR TITLE
Update translationcontroller.php

### PR DESCRIPTION
**Pull request by rakekniven**
Improve english wording and fixed typo (average).

### CODE REVIEW

**Comment by rakekniven** [comment]
Any chance to work on my PR. Would like to close open Transifex issues. Thanks.

**Comment by brantje** [comment]
I'll copy your changes to PR #289 since they are not signed.

**Comment by rakekniven** [comment]
Could you provide some more information about "signed". Always like to learn something.

**Comment by brantje** [comment]
[Signing your commits](https://help.github.com/articles/signing-commits-using-gpg/)

**Pull request closed without merging**
