### PR TITLE
Update part.admin.php

### PR DESCRIPTION
**Pull request by rakekniven**
Fixed very small l10n issue

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by brantje** [comment]
Your commit is not properly signed and missing a [verified] tag. Can you please fix this?

**Comment by rakekniven** [comment]
See https://github.com/nextcloud/passman-webextension/issues/107

I contributed changes to nextcloud server and people trust me. Still do agree to the signing enforcement for non functional code changes.

**Comment by animalillo** [comment]
Code is code, even if code is only text it is still code.

**Comment by rakekniven** [comment]
Yes, but the server / core people have a good solution for signing in my eyes.
At the moment for me this is blocking me to fix issues with passman.

**Comment by brantje** [comment]
Did you read our [contribution guidelines](https://github.com/nextcloud/passman/blob/master/CONTRIBUTING.md)?

**Comment by brantje** [comment]
Due lack of signing i squashed merged this. Ref 12e23dec782fea7b804b3408dd8328629f91dd53

**Pull request closed without merging**
