### PR TITLE
Update translationcontroller.php

### PR DESCRIPTION
**Pull request by rakekniven**
Improved english wording.
Result of discussion at transifex

### CODE REVIEW

**Comment by animalillo** [comment]
but but but
my passwords are precious! :<

**Comment by rakekniven** [comment]
Hello, spoke to english and american natives (from my company) and both voted for "valuable".
Feel free to deny PR. It is your project

**Comment by enoch85** [comment]
http://s2.quickmeme.com/img/df/df0ff33f266f32214d219b927452e45fc1dffeaee2a32c2df03cac793d08d36a.jpg

**Comment by animalillo** [comment]
wajajaja, exactly, we will think if merging it tho

**Comment by brantje** [comment]
Closing this PR is also NOT signed.

**Pull request closed without merging**
