### PR TITLE
l10n: Removal of backslash and spaces

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Comment by rakekniven** [comment]
@Valdnet Are you sure the removing of the slashes will work? Isn't a escaping for " ?

**Comment by Valdnet** [comment]
@rakekniven I'm sure 😉. The text string is enclosed in an apostrophe `'`, so you can use quotation marks `"`. In l10n files, the backslash `\` is automatically added, so it doesn't conflict either:
https://github.com/nextcloud/passman/blob/139aed59b83f18bd1ddef72b9f064718701607d6/l10n/pl.json#L173
In the current version it makes translation difficult for translators in Transifex and a backslash is added many times in l10n files:
https://github.com/nextcloud/passman/blob/48ffe8738e05374876c6b5a8ad92aea62e907d74/l10n/de.js#L175

**Review by rakekniven — APPROVED** [review]

**Comment by rakekniven** [comment]
Cannot merge it :-(

**Comment by Valdnet** [comment]
@animalillo can you merge?

**Comment by Valdnet** [comment]
ping @brantje @newhinton @animalillo

**Pull request merged**
