### PR TITLE
Fix import, wrong JSON field for username

### PR DESCRIPTION
**Pull request by Oliv4945**

### CODE REVIEW

**Comment by newhinton** [comment]
@Oliv4945 Can you explain how i can reproduce this bug so that i can test it properly?

**Comment by Oliv4945** [comment]
@newhinton : export credentials in passman json format, then try to import them in another vault

**Comment by newhinton** [comment]
thanks!

**Comment by newhinton** [comment]
@Oliv4945 Also, could you please sign your commit?

**Comment by newhinton** [comment]
@Oliv4945 I can reproduce the error and will merge your pull request as soon as you sign it :) I would kindly ask you to do so until Friday, because that will be the last day we accept changes for the next release ;)

**Comment by Oliv4945** [comment]
Ok, I'll try to do it by the end of the week. Sorry I did not read contributing for such small change.
Do you prefer a push force or I delete this PR and do another one ?

**Comment by newhinton** [comment]
Either one is fine, do what is less hassle for you ;)
and don't worry, i made the same mistake the first time ;)

**Pull request merged**
