### PR TITLE
Add Padlock importer

### PR DESCRIPTION
**Pull request by bingen**
Importer for the CSV export files of Padlock password manager:
https://padlock.io/

Signed-off-by: ßingen <bingentxu@gmail.com>

### CODE REVIEW

**Comment by animalillo** [comment]
it looks good to me, but this comment worries me: "TODO: Allow for new lines and commas in values"

**Comment by bingen** [comment]
So, the way it is now, if a password (or any other custom field) has a comma or a new line, it won't work. It's something to be improved, but I was able to import ~90 entries just removing one that has commas (which I imported manually) and manually deleting new lines from another one in advance. As commas and new lines are not so common in passwords, I think it's still useful. Let me know if I can clarify any further.

**Comment by animalillo** [comment]
I think that for it to be merged into the production system it should work if a password has a coma too!

You might only have 1 matching that pattern, but somebody might have a novel phrase as it's password! Who knows!

Have you tried if that works with the generic CSV importer?

**Comment by animalillo** [comment]
Also note that custom fields are custom for a reason, people might store something like that typical recovery questions having comas or something.

**Comment by bingen** [comment]
Ya, I tried with the generic CSV password and it wasn't working.

**Comment by bingen** [comment]
Ok, I was unlucky: I just picked the [first one by alphabetical order](https://github.com/nextcloud/passman/blob/master/js/importers/importer-dashlanecsv.js) as an example, which is not using `PassmanImporter.readCsv`.
Replacing this by #325

**Pull request closed without merging**
