### PR TITLE
Makes placeholder file an valid php file to not produce an http output

### PR DESCRIPTION
**Pull request by tacruc**
Makes placeholder file an valid php file to not produce an http output

Fixes nextcloud/server#7423

Signed-off-by: Arne Hamann <kontakt+github@arne.email>

### CODE REVIEW

**Comment by tacruc** [comment]
@Brantje or @Animalillo could you do a review or add a review flag?
This file is spamming the logs discriped in here nextcloud/server#7423

**Comment by brantje** [comment]
Ye, merged #433

**Comment by tacruc** [comment]
@brantje can't see the connection to the Issue you mention.

**Comment by bthall** [comment]
Seems like this should be re-opened. I'm on 13.0.4 and this issue is still occurring.

**Comment by Riscue** [comment]
Same here. The issue is on

**Comment by Verklicker** [comment]
Same problem here. 13.0.4 and 2.1.4

**Comment by ymybe** [comment]
13.0.5  passmann 2.14, php(fpm via proxy fcgi) 7.2.8, mariadb 10.3.8, apache 2.4.34 redis:4-alpine docker (as of 4aug18) , linux 4.17.12 the log spam still persists.

`Cannot modify header information - headers already sent by (output started at /var/www/cloud/apps/passman/personal.php:1) at /var/www/cloud/lib/private/AppFramework/Http/Output.php#69`

~4 times each refresh of log page

**Comment by tacruc** [comment]
Is it possible to reopen this PR. https://github.com/nextcloud/server/issues/7423#issuecomment-369210384 is still active.

**Comment by tacruc** [comment]
OK found the fixed with https://github.com/nextcloud/passman/commit/0b6f427adc4a941e6832366cf534580a18373054#diff-00f3ec719a69951e82c34155f3a50b44

**Pull request closed without merging**
