### PR TITLE
Language: Some strings fixed.

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by brantje** [comment]
Can you sign the commit?

**Comment by comradekingu** [comment]
@brantje I haven't had to thus far, so I don't see the point. There are no copyrightable changes made in this PR.

**Comment by brantje** [comment]
```
If you want to contribute make sure the commits are verified.
You can read how to GPG sign you commits here.

Issue's / Feature requests not honoring the template will be closed instantly.
```

**Comment by brantje** [comment]
Not signed

**Pull request closed without merging**
